/*2015-11-10    图像表格*/
CREATE TABLE `T_STATIC_IMAGES` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(20) DEFAULT NULL COMMENT '图像名称',
  `url` varchar(255) DEFAULT NULL COMMENT '图像链接',
  `expired` tinyint(1) DEFAULT NULL COMMENT '图像是否过期',
  `createTime` datetime DEFAULT NULL,
  `updateTime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ind_exp` (`expired`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

/* 2015-11-19   用户权限表 */
CREATE TABLE `td_user_authority` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` varchar(32) NOT NULL COMMENT '用户ID',
  `token` varchar(32) NOT NULL COMMENT '身份令牌',
  `expiredTime` datetime NOT NULL COMMENT 'token过期时间',
  `createTime` datetime NOT NULL COMMENT '记录创建时间',
  `updateTime` datetime NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ind_uid` (`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

/* 2015-11-20 保险公司表 */
ALTER TABLE `T_INSURANCE` ADD COLUMN `TRANS_CHANNEL` varchar(2) AFTER `SIGN_KEY`;

/* 2015-11-20 用户私有消息及公有消息表 */
CREATE TABLE `td_user_private_message` (
  `msgId` bigint(20) NOT NULL AUTO_INCREMENT,
  `uid` varchar(32) NOT NULL COMMENT '用户 ID',
  `title` varchar(255) NOT NULL COMMENT '消息标题',
  `content` varchar(2000) NOT NULL COMMENT '消息内容',
  `isRead` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已读的标识',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已删除的标识',
  `createTime` datetime DEFAULT NULL COMMENT '记录创建时间',
  `updateTime` datetime DEFAULT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`msgId`),
  KEY `ind_uid` (`uid`),
  KEY `ind_uid_read` (`uid`,`isRead`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `td_public_message` (
  `msgId` bigint(20) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL COMMENT '消息标题',
  `content` varchar(2000) DEFAULT NULL COMMENT '消息内容',
  `createTime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateTime` datetime DEFAULT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`msgId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* 2015-11-23 用户表增加推送的 clientId */
ALTER TABLE `T_USER` ADD COLUMN `CLIENT_ID` varchar(64) AFTER `CERTI_IS_VALID`, 
    ADD COLUMN `APP_TYPE` varchar(10) AFTER `CLIENT_ID`;
 
/* 2015-11-24 用户消息表增加 target 和 url */
ALTER TABLE `td_public_message` DROP COLUMN `url`, DROP COLUMN `target`, ADD COLUMN `url` varchar(255) AFTER `content`,
ADD COLUMN `target` varchar(25) AFTER `url`, CHANGE COLUMN `createTime` `createTime` datetime DEFAULT NULL COMMENT '创建时间' AFTER `target`, CHANGE COLUMN `updateTime` `updateTime` datetime DEFAULT NULL COMMENT '最后更新时间' AFTER `createTime`;

ALTER TABLE `td_user_private_message` ADD COLUMN `url` varchar(255) COMMENT '消息映射的 url' AFTER `content`, 
ADD COLUMN `target` varchar(25) COMMENT '消息target' AFTER `url`, CHANGE COLUMN `isRead` `isRead` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已读的标识' AFTER `target`, CHANGE COLUMN `deleted` `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已删除的标识' AFTER `isRead`, CHANGE COLUMN `createTime` `createTime` datetime DEFAULT NULL COMMENT '记录创建时间' AFTER `deleted`, CHANGE COLUMN `updateTime` `updateTime` datetime DEFAULT NULL COMMENT '最后更新时间' AFTER `createTime`;

/* 2015-11-30 产品增加 可贷比例、已购买人数 */
ALTER TABLE `T_PRODUCT` ADD COLUMN `RATE_LOANABLE` int COMMENT '可贷比例' AFTER `IS_RECOMMEND`;
ALTER TABLE `T_PRODUCT` ADD COLUMN `INSURED_NUM` int COMMENT '已购买人数' AFTER `RATE_LOANABLE`;
/* 2015-11-30 产品详情增加 起息日、赎回方式 */
ALTER TABLE `T_PRODUCT_DETAIL` ADD COLUMN `VALUE_DATE` varchar(255) COMMENT '起息日' AFTER `UPDATE_DATE`, 
ADD COLUMN `REDEMPTION_MODE` varchar(255) COMMENT '赎回方式' AFTER `valueDate`;

/* 2015-12-01 保单表增加 年化预期收益率、当前累计总收益 、昨日收益、可贷额度*/
ALTER TABLE `T_POLICY_MASTER` ADD COLUMN `EXPECT_RATE` float(8,0) COMMENT '预期年化收益率' AFTER `TOTAL_REVENUE`, 
CHANGE COLUMN `PREM` `PREM` decimal(15,2) NOT NULL COMMENT '单价' AFTER `EXPECT_RATE`, CHANGE COLUMN `REPAY_AMOUNT` `REPAY_AMOUNT` decimal(15,2) DEFAULT NULL COMMENT '预期赎回金额' AFTER `PREM`, 
CHANGE COLUMN `SEND_CODE` `SEND_CODE` varchar(32) DEFAULT NULL COMMENT '保险公司投保单号码' AFTER `REPAY_AMOUNT`, CHANGE COLUMN `POLICY_CODE` `POLICY_CODE` varchar(32) DEFAULT NULL COMMENT '保险公司保单号码' AFTER `SEND_CODE`, 
CHANGE COLUMN `COMMENTS` `COMMENTS` varchar(200) DEFAULT NULL AFTER `POLICY_CODE`, CHANGE COLUMN `ISVALID` `ISVALID` varchar(1) NOT NULL AFTER `COMMENTS`, CHANGE COLUMN `CREATE_DATE` `CREATE_DATE` datetime NOT NULL AFTER `ISVALID`, 
CHANGE COLUMN `POLICY_URL` `POLICY_URL` varchar(300) DEFAULT NULL COMMENT '电子保单URL' AFTER `CREATE_DATE`, CHANGE COLUMN `UPDATE_DATE` `UPDATE_DATE` datetime NOT NULL AFTER `POLICY_URL`, 
CHANGE COLUMN `RELATION` `RELATION` varchar(2) DEFAULT NULL COMMENT '投被保险人关系' AFTER `UPDATE_DATE`, ADD COLUMN `ACCUMULATED_INCOME` decimal(15,4) COMMENT '当前累计总收益' AFTER `RELATION`;

ALTER TABLE `T_POLICY_MASTER` ADD COLUMN `YESDAY_INCOME` decimal(15,4) COMMENT '昨日收益' AFTER `ACCUMULATED_INCOME`, ADD COLUMN `LOANABLE_AMOUNT` decimal(15,0) COMMENT '可贷额度' AFTER `YESDAY_INCOME`;

/* 2015-12-03 资金账户表增加交易密码设置状态 */
ALTER TABLE `T_USER_ACCOUNT` ADD COLUMN `PASSWORD_STATUS` varchar(2) NOT NULL COMMENT '交易密码设置的状态' AFTER `STATUS`, CHANGE COLUMN `ISVALID` `ISVALID` varchar(1) NOT NULL AFTER `PASSWORD_STATUS`, CHANGE COLUMN `CREATE_DATE` `CREATE_DATE` datetime NOT NULL AFTER `ISVALID`, CHANGE COLUMN `UPDATE_DATE` `UPDATE_DATE` datetime NOT NULL AFTER `CREATE_DATE`;

/* 2015-12-08 资金账户表增加银行识别ID*/
LTER TABLE `T_USER_ACCOUNT` CHANGE COLUMN `VIRTUAL_ACCOUNT_NO` `VIRTUAL_ACCOUNT_NO` varchar(32) DEFAULT NULL COMMENT '虚拟账户号码', ADD COLUMN `VIRTUAL_ACCOUNT_ID` varchar(255) AFTER `VIRTUAL_ACCOUNT_NO`, CHANGE COLUMN `SURR_AMOUNT` `SURR_AMOUNT` decimal(24,8) NOT NULL COMMENT '退保金额' AFTER `VIRTUAL_ACCOUNT_ID`, CHANGE COLUMN `REPAY_AMOUNT` `REPAY_AMOUNT` decimal(24,8) NOT NULL COMMENT '还款金额' AFTER `SURR_AMOUNT`, CHANGE COLUMN `STATUS` `STATUS` varchar(2) NOT NULL AFTER `REPAY_AMOUNT`, CHANGE COLUMN `PASSWORD_STATUS` `PASSWORD_STATUS` varchar(2) NOT NULL COMMENT '交易密码设置的状态' AFTER `STATUS`, CHANGE COLUMN `ISVALID` `ISVALID` varchar(1) NOT NULL AFTER `PASSWORD_STATUS`, CHANGE COLUMN `CREATE_DATE` `CREATE_DATE` datetime NOT NULL AFTER `ISVALID`, CHANGE COLUMN `UPDATE_DATE` `UPDATE_DATE` datetime NOT NULL AFTER `CREATE_DATE`;

/* 2015-12-09 南粤银行交易响应数据表 */
CREATE TABLE tb_trans_record_b (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `userId` varchar(32) COMMENT '用户名',
    `transId` varchar(32) NOT NULL COMMENT 'dy的交易流水号',
    `transType` varchar(2) NOT NULL COMMENT '交易类型',
    `status` varchar(32) NOT NULL COMMENT '交易状态',
    `errorMsg` varchar(255) COMMENT '错误信息',
    `bankCode` varchar(32) NOT NULL COMMENT '银行代码',
    `bankTransId` varchar(64) COMMENT '银行交易流水号',
    `channelNo` varchar(32) NOT NULL COMMENT '渠道号',
    `sign` varchar(255) COMMENT '银行签名',
    `createTime` datetime COMMENT '创建时间',
    `updateTime` datetime COMMENT '更新时间',
    PRIMARY KEY (`id`),
    INDEX `ind_user_id` (`userId`) comment '',
    INDEX `ind_bank_code` (`bankCode`) comment ''
) ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='';

/* 2015-12-14 用户账户增加冻结资金的字段 */
ALTER TABLE `T_USER_ACCOUNT` CHANGE COLUMN `ACCOUNT_AMOUNT` `ACCOUNT_AMOUNT` decimal(24,2) NOT NULL COMMENT '账户总价值', CHANGE COLUMN `ACCOUNT_BALANCE` `ACCOUNT_BALANCE` decimal(24,2) NOT NULL COMMENT '账户现金余额', ADD COLUMN `FROZEN_AMOUNT` decimal(24,2) COMMENT '冻结的总金额' AFTER `ACCOUNT_BALANCE`, CHANGE COLUMN `POLICY_VALUE` `POLICY_VALUE` decimal(24,2) NOT NULL COMMENT '保单价值' AFTER `FROZEN_AMOUNT`, CHANGE COLUMN `LOAN_AMOUNT` `LOAN_AMOUNT` decimal(24,2) NOT NULL COMMENT '借款金额' AFTER `POLICY_VALUE`, CHANGE COLUMN `VIRTUAL_ACCOUNT_NO` `VIRTUAL_ACCOUNT_NO` varchar(32) DEFAULT NULL COMMENT '虚拟账户号码' AFTER `LOAN_AMOUNT`, CHANGE COLUMN `VIRTUAL_ACCOUNT_ID` `VIRTUAL_ACCOUNT_ID` varchar(255) DEFAULT NULL AFTER `VIRTUAL_ACCOUNT_NO`, CHANGE COLUMN `SURR_AMOUNT` `SURR_AMOUNT` decimal(24,2) NOT NULL COMMENT '退保金额' AFTER `VIRTUAL_ACCOUNT_ID`, CHANGE COLUMN `REPAY_AMOUNT` `REPAY_AMOUNT` decimal(24,2) NOT NULL COMMENT '还款金额' AFTER `SURR_AMOUNT`, CHANGE COLUMN `STATUS` `STATUS` varchar(2) NOT NULL AFTER `REPAY_AMOUNT`, CHANGE COLUMN `PASSWORD_STATUS` `PASSWORD_STATUS` varchar(2) NOT NULL COMMENT '交易密码设置的状态' AFTER `STATUS`, CHANGE COLUMN `ISVALID` `ISVALID` varchar(1) NOT NULL AFTER `PASSWORD_STATUS`, CHANGE COLUMN `CREATE_DATE` `CREATE_DATE` datetime NOT NULL AFTER `ISVALID`, CHANGE COLUMN `UPDATE_DATE` `UPDATE_DATE` datetime NOT NULL AFTER `CREATE_DATE`;

/* 2015-12-14 保单表增加投保单号 */
ALTER TABLE `T_POLICY_MASTER` ADD COLUMN `PROPOSAL_NO` varchar(32) COMMENT '投保单号' AFTER `POLICY_CODE`, CHANGE COLUMN `COMMENTS` `COMMENTS` varchar(200) DEFAULT NULL AFTER `PROPOSAL_NO`, CHANGE COLUMN `ISVALID` `ISVALID` varchar(1) NOT NULL AFTER `COMMENTS`, CHANGE COLUMN `CREATE_DATE` `CREATE_DATE` datetime NOT NULL AFTER `ISVALID`, CHANGE COLUMN `POLICY_URL` `POLICY_URL` varchar(300) DEFAULT NULL COMMENT '电子保单URL' AFTER `CREATE_DATE`, CHANGE COLUMN `UPDATE_DATE` `UPDATE_DATE` datetime NOT NULL AFTER `POLICY_URL`, CHANGE COLUMN `RELATION` `RELATION` varchar(2) DEFAULT NULL COMMENT '投被保险人关系' AFTER `UPDATE_DATE`, CHANGE COLUMN `ACCUMULATED_INCOME` `ACCUMULATED_INCOME` decimal(15,4) DEFAULT NULL COMMENT '当前累计总收益' AFTER `RELATION`, CHANGE COLUMN `YESDAY_INCOME` `YESDAY_INCOME` decimal(15,4) DEFAULT NULL COMMENT '昨日收益' AFTER `ACCUMULATED_INCOME`, CHANGE COLUMN `LOANABLE_AMOUNT` `LOANABLE_AMOUNT` decimal(15,0) DEFAULT NULL COMMENT '可贷额度' AFTER `YESDAY_INCOME`;

/* 2015-12-17 用户表增加唯一索引 */
ALTER TABLE `T_USER` ADD UNIQUE `index_acc` (`USER_ACCOUNT`) comment '', ADD UNIQUE `index_tel` (`USER_MOBILEPHONE`) comment '', ADD UNIQUE `index_certi` (`CERTI_CODE`) comment '';
/* 2015-12-17 账户表增加唯一索引*/
ALTER TABLE `T_USER_ACCOUNT` ADD UNIQUE `ind_acc_id` (`USER_ACCOUNT_ID`) comment '', ADD UNIQUE `ind_uid` (`USER_ID`) comment '';

/* 2015-12-21 产品增加犹豫期 */
ALTER TABLE `T_PRODUCT` ADD COLUMN `HESITATE_TERM` int COMMENT '犹豫期（天）' AFTER `INSURED_NUM`;

/* 2016-01-27 用户账户增加银行代码字段 */
ALTER TABLE `T_USER_ACCOUNT` ADD COLUMN `BANKCODE` varchar(10) AFTER `VIRTUAL_ACCOUNT_ID`, CHANGE COLUMN `SURR_AMOUNT` `SURR_AMOUNT` decimal(24,2) NOT NULL COMMENT '退保金额' AFTER `BANKCODE`, CHANGE COLUMN `REPAY_AMOUNT` `REPAY_AMOUNT` decimal(24,2) NOT NULL COMMENT '还款金额' AFTER `SURR_AMOUNT`, CHANGE COLUMN `STATUS` `STATUS` varchar(2) NOT NULL AFTER `REPAY_AMOUNT`, CHANGE COLUMN `PASSWORD_STATUS` `PASSWORD_STATUS` varchar(2) NOT NULL COMMENT '交易密码设置的状态' AFTER `STATUS`, CHANGE COLUMN `ISVALID` `ISVALID` varchar(1) NOT NULL AFTER `PASSWORD_STATUS`, CHANGE COLUMN `CREATE_DATE` `CREATE_DATE` datetime NOT NULL AFTER `ISVALID`, CHANGE COLUMN `UPDATE_DATE` `UPDATE_DATE` datetime NOT NULL AFTER `CREATE_DATE`;


/*2016-01-30 T_USER_PAYACCOUNT 修改非空字段*/
ALTER TABLE `T_USER_PAYACCOUNT` CHANGE COLUMN `BANK_PROVINCE` `BANK_PROVINCE` varchar(50) COMMENT '开户行所在省', CHANGE COLUMN `BANK_CITY` `BANK_CITY` varchar(50) COMMENT '开户行所在市';

/*2016-01-30 银行账户和虚拟账号设置唯一索引*/
ALTER TABLE `T_USER_ACCOUNT` ADD UNIQUE `ind_acc_no` (VIRTUAL_ACCOUNT_NO);
ALTER TABLE `T_USER_PAYACCOUNT`  ADD UNIQUE `ind_acc_no` USING BTREE (ACCOUNT_NO);

/* 2016-01-30 与银行交易记录表设置交易流水号为唯一索引 */
ALTER TABLE `tb_trans_record_b` ADD UNIQUE `ind_transId` (`transId`) comment '';
/*2016-02-1 账户金额变动表  修改非空字段*/
ALTER TABLE `T_USER_ACCOUNT_DETAIL` CHANGE COLUMN `USER_ACCOUNT_DETAIL_ID` `USER_ACCOUNT_DETAIL_ID` varchar(32), CHANGE COLUMN `BUSINESS_ID` `BUSINESS_ID` varchar(32);=======

/* 2016-01-30 新建版本记录表 */
CREATE TABLE  `td_version_record`(
    `id` int NOT NULL AUTO_INCREMENT,
    `version` varchar(32),
    `value` bigint,
    `createTime` datetime,
    PRIMARY KEY (`id`)
) ENGINE=`InnoDB` COMMENT='';
/*2016-03-02 南粤身份证类型更改，增加长度*/
ALTER TABLE `T_USER` CHANGE COLUMN `CERTI_TYPE` `CERTI_TYPE` varchar(20) DEFAULT NULL COMMENT '证件类型';
/*2016-03-20 交易记录表增加用户token 和 insureId TRANS_PRODUCT_NAME*/
ALTER TABLE `T_BUSINESS_TRANS` ADD COLUMN `TRANS_USER_TOKEN` varchar(255) DEFAULT NULL COMMENT '用户token';
ALTER TABLE `T_BUSINESS_TRANS` ADD COLUMN `TRANS_INSURE_ID` varchar(255) DEFAULT NULL COMMENT '保单号';
ALTER TABLE `T_BUSINESS_TRANS` CHANGE COLUMN `TRANS_PRODUCT` `TRANS_PRODUCT_NAME` varchar(255) DEFAULT NULL COMMENT '购买产品信息';

