jenkins-plugins:
  image: rancher/jenkins-plugins:v0.1.1
jenkins-datavolume:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - chown
  - -R
  - 1000:1000
  - /var/jenkins_home
  image: busybox
  volumes:
  - /data/var/jenkins_home:/var/jenkins_home
  - /etc/timezone:/etc/localtime
  - /etc/timezone:/etc/timezone
jenkins-primary:
  ports:
  - 8082:8080/tcp
  labels:
    io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
    io.rancher.container.hostname_override: container_name
  entrypoint:
  - /usr/share/jenkins/rancher/jenkins.sh
  image: jenkins:1.642.2
  environment:
  - TZ=Asia/Shanghai
  volumes_from:
  - jenkins-plugins
  - jenkins-datavolume
